# Generated by Django 5.1.2 on 2024-11-03 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.article')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=32)),
                ('sender_address', models.CharField(max_length=255)),
                ('receiver_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'in-transit'), ('INBOUND_SCAN', 'inbound-scan'), ('DELIVERY', 'delivery'), ('TRANSIT', 'transit'), ('SCANNED', 'scanned')], max_length=12)),
                ('articles', models.ManyToManyField(related_name='shipments', through='shipments.ArticleShipmentItem', to='shipments.article')),
            ],
        ),
        migrations.AddField(
            model_name='articleshipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.shipment'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['carrier', 'tracking_number'], name='carrier_tracking_number_index'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('carrier', 'tracking_number'), name='unique_carrier_tracking_number'),
        ),
        migrations.AddConstraint(
            model_name='articleshipmentitem',
            constraint=models.UniqueConstraint(fields=('article', 'shipment'), name='unique_article_shipment'),
        ),
    ]
