# Generated by Django 5.1.2 on 2024-11-03 22:05

import shipments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(max_length=255, validators=[shipments.validators.validate_comma_separated_address]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_address',
            field=models.CharField(max_length=255, validators=[shipments.validators.validate_comma_separated_address]),
        ),
    ]
